'use strict';

// skill-trace lesson store — one OKF-style markdown file per lesson.
//
// This module owns the on-disk format (schema 2) and every operation on a store
// directory: ids, hashing, parse/serialize, load, create, upsert-with-dedup,
// delete-with-tombstone, rollup regeneration, legacy (schema 1) migration, and
// the project → global sync that the hooks and the log-lesson skill call.
// It has zero dependencies and no side effects at require time. Run directly it
// is a small CLI; required, it exposes pure functions for the server, hooks and
// tests. See docs/superpowers/specs/2026-10-02-okf-lesson-store-design.md.

const fs = require('fs');
const path = require('path');
const os = require('os');
const crypto = require('crypto');
const { execFileSync } = require('child_process');
const trust = require('./trust.js');

const SCHEMA = 2;
const LESSONS_DIR = 'lessons';
const TOMBSTONES = 'tombstones.txt';
const GENERATED_MARK = '<!-- generated by skill-trace';
const RECURRENCE_WINDOW_DAYS = 7;
const DEFAULT_SOURCE_RE = /docs[/\\]skills\.md$/i;

// ── Paths ─────────────────────────────────────────────────────────────────────
// The ONE place the store location is defined. A future move (e.g. to a neutral
// `.skill-trace/`) is a change here and nowhere else.

function storePaths({ home = os.homedir(), projectDir = process.cwd() } = {}) {
  return {
    global:  process.env.SKILL_TRACE_GLOBAL_STORE  || path.join(home, '.claude', 'skill-trace'),
    project: process.env.SKILL_TRACE_PROJECT_STORE || path.join(projectDir, '.claude', 'skill-trace'),
    legacyGlobalMd:  process.env.GLOBAL_SKILLS_MD_PATH || path.join(home, '.claude', 'global-skills.md'),
    legacyProjectMd: path.join(projectDir, 'docs', 'skills.md'),
  };
}

// ── ULID ──────────────────────────────────────────────────────────────────────
// 26 chars, Crockford base32: 10 chars of ms timestamp + 16 chars of randomness.
// Monotonic within a process: same-millisecond ids increment the random part so
// they still sort in creation order.

const B32 = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
let lastTime = 0;
let lastRand = null;

function encodeTime(ms) {
  let out = '';
  for (let i = 0; i < 10; i++) { out = B32[ms % 32] + out; ms = Math.floor(ms / 32); }
  return out;
}

function ulid(now = Date.now()) {
  if (now === lastTime && lastRand) {
    for (let i = lastRand.length - 1; i >= 0; i--) {
      if (lastRand[i] === 255) { lastRand[i] = 0; } else { lastRand[i]++; break; }
    }
  } else {
    lastTime = now;
    lastRand = crypto.randomBytes(10);
  }
  let bits = 0n;
  for (const b of lastRand) bits = (bits << 8n) | BigInt(b);
  let rand = '';
  for (let i = 0; i < 16; i++) { rand = B32[Number(bits & 31n)] + rand; bits >>= 5n; }
  return encodeTime(now) + rand;
}

// ── Body normalization + hash ─────────────────────────────────────────────────
// Mirrors server.js entryKey(): trimmed lines, blanks dropped, legacy
// **Project:** lines ignored. Whitespace-only edits do not change the hash.

function normalizeBody(body) {
  return String(body).split('\n')
    .map(l => l.trim())
    .filter(l => l && !l.startsWith('**Project:**'))
    .join('\n');
}

function bodyHash(body) {
  return crypto.createHash('sha1').update(normalizeBody(body), 'utf8').digest('hex').slice(0, 12);
}

// ── Frontmatter (minimal YAML subset) ─────────────────────────────────────────
// Supported: `key: scalar`, `key: [a, b]`, quoted strings, trailing `# comment`
// on unquoted values. Nothing else, on purpose — no YAML library.

const LIST_KEYS = new Set(['stack', 'projects']);
const INT_KEYS  = new Set(['schema', 'seen']);
const KEY_ORDER = ['id', 'type', 'schema', 'title', 'date', 'stack', 'projects', 'seen', 'generated_by', 'created', 'updated', 'hash'];

function parseScalar(raw) {
  let v = raw.trim();
  if (/^".*"$/.test(v)) return JSON.parse(v);
  if (/^'.*'$/.test(v)) return v.slice(1, -1).replace(/''/g, "'");
  v = v.replace(/\s+#.*$/, '').trim();
  return v;
}

function parseList(raw) {
  const inner = raw.trim().replace(/^\[/, '').replace(/\]\s*(#.*)?$/, '');
  return inner.split(',').map(x => parseScalar(x)).filter(Boolean);
}

function quoteIfNeeded(s) {
  s = String(s);
  if (/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/.test(s)) return s; // ISO timestamps read fine unquoted
  if (s === '' || /[:#\[\]{}"'\n]|^\s|\s$|^[-?&*!|>%@`]/.test(s)) return JSON.stringify(s);
  return s;
}

function parseLesson(text) {
  text = String(text).replace(/^﻿/, '').replace(/\r\n/g, '\n');
  const m = text.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) throw new Error('missing frontmatter');
  const meta = {};
  for (const line of m[1].split('\n')) {
    if (!line.trim() || line.trim().startsWith('#')) continue;
    const kv = line.match(/^([A-Za-z_][\w-]*):\s*(.*)$/);
    if (!kv) throw new Error(`bad frontmatter line: ${line}`);
    const [, key, raw] = kv;
    if (LIST_KEYS.has(key)) meta[key] = raw.trim().startsWith('[') ? parseList(raw) : (parseScalar(raw) ? [parseScalar(raw)] : []);
    else if (INT_KEYS.has(key)) meta[key] = parseInt(parseScalar(raw), 10);
    else meta[key] = parseScalar(raw);
  }
  if (!meta.id || !meta.title || !meta.date) throw new Error('frontmatter needs id, title, date');
  const body = m[2].replace(/^\n+/, '').trimEnd() + '\n';
  return {
    id: meta.id,
    type: meta.type || 'Lesson',
    schema: meta.schema || SCHEMA,
    title: meta.title,
    date: meta.date,
    stack: (meta.stack || []).map(s => s.toLowerCase()),
    projects: meta.projects || [],
    seen: Number.isFinite(meta.seen) ? meta.seen : 1,
    ...(meta.generated_by ? { generated_by: meta.generated_by } : {}),
    created: meta.created || '',
    updated: meta.updated || '',
    hash: meta.hash || '',
    body,
  };
}

function serializeLesson(l) {
  const lines = ['---'];
  for (const k of KEY_ORDER) {
    const v = l[k];
    if (v === undefined || v === null) continue;
    if (LIST_KEYS.has(k)) lines.push(`${k}: [${(v || []).map(quoteIfNeeded).join(', ')}]`);
    else lines.push(`${k}: ${INT_KEYS.has(k) ? v : quoteIfNeeded(v)}`);
  }
  lines.push('---', '');
  return lines.join('\n') + String(l.body).replace(/\r\n/g, '\n').trimEnd() + '\n';
}

// ── Sections (same regex family as the viewer) ────────────────────────────────

function extractSection(body, label) {
  const re = new RegExp(`\\*\\*${label}:\\*\\*([\\s\\S]*?)(?=\\n\\*\\*[A-Z]|$)`, 'i');
  const m = body.match(re);
  return m ? m[1].trim() : null;
}

function sections(l) {
  return {
    problem:  extractSection(l.body, 'Problem'),
    solution: extractSection(l.body, 'Solution'),
    takeaway: extractSection(l.body, 'Takeaway'),
  };
}

// ── Filenames ─────────────────────────────────────────────────────────────────

function slugify(title) {
  return String(title).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40).replace(/-+$/, '') || 'lesson';
}

// The id's LAST 8 chars are the random part — unique even for same-ms ids.
function lessonFilename(l) {
  return `${l.date}-${slugify(l.title)}--${l.id.slice(-8)}.md`;
}

// ── Store I/O ─────────────────────────────────────────────────────────────────

function lessonsDir(dir) { return path.join(dir, LESSONS_DIR); }

function ensureStore(dir) {
  fs.mkdirSync(lessonsDir(dir), { recursive: true });
}

function nowIso() { return new Date().toISOString().replace(/\.\d{3}Z$/, 'Z'); }

function readTombstones(dir) {
  try {
    return new Set(fs.readFileSync(path.join(dir, TOMBSTONES), 'utf8').split('\n').map(s => s.trim()).filter(Boolean));
  } catch { return new Set(); }
}

function appendTombstone(dir, id) {
  ensureStore(dir);
  fs.appendFileSync(path.join(dir, TOMBSTONES), id + '\n', 'utf8');
}

// Returns { lessons, warnings }. Each lesson carries `file` (basename) and
// `edited` (true when the stored hash no longer matches the body — i.e. the file
// was changed outside the tool). Unparsable files are skipped, not fatal.
function loadStore(dir) {
  const out = { lessons: [], warnings: [] };
  const ld = lessonsDir(dir);
  if (!fs.existsSync(ld)) return out;
  for (const f of fs.readdirSync(ld).filter(f => f.endsWith('.md')).sort()) {
    try {
      const l = parseLesson(fs.readFileSync(path.join(ld, f), 'utf8'));
      l.file = f;
      l.edited = !!l.hash && l.hash !== bodyHash(l.body);
      out.lessons.push(l);
    } catch (err) {
      out.warnings.push(`${f}: ${err.message}`);
    }
  }
  out.lessons.sort((a, b) => b.date.localeCompare(a.date) || b.id.localeCompare(a.id));
  return out;
}

function writeLesson(dir, l) {
  ensureStore(dir);
  const file = lessonFilename(l);
  // retitled lesson: remove the old file carrying the same id
  for (const f of fs.readdirSync(lessonsDir(dir))) {
    if (f !== file && f.endsWith(`--${l.id.slice(-8)}.md`)) {
      try { if (parseLesson(fs.readFileSync(path.join(lessonsDir(dir), f), 'utf8')).id === l.id) fs.unlinkSync(path.join(lessonsDir(dir), f)); } catch {}
    }
  }
  fs.writeFileSync(path.join(lessonsDir(dir), file), serializeLesson(l), 'utf8');
  l.file = file;
  l.edited = false;
  return l;
}

function findById(dir, id) {
  return loadStore(dir).lessons.find(l => l.id === id) || null;
}

function stripRuntime(l) { const c = { ...l }; delete c.file; delete c.edited; return c; }

// ── Create ────────────────────────────────────────────────────────────────────

function createLesson(dir, { title, date, stack = [], body, project, projects, generatedBy, now } = {}) {
  if (!title || !String(title).trim()) throw new Error('title required');
  if (!body || !String(body).trim()) throw new Error('body required');
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date || '')) throw new Error('date must be YYYY-MM-DD');
  const ts = now || nowIso();
  const l = {
    id: ulid(),
    type: 'Lesson',
    schema: SCHEMA,
    title: String(title).trim(),
    date,
    stack: [...new Set(stack.map(s => String(s).trim().toLowerCase()).filter(Boolean))],
    projects: projects || (project ? [project] : []),
    seen: 1,
    ...(generatedBy ? { generated_by: generatedBy } : {}),
    created: ts,
    updated: ts,
    body: String(body).replace(/\r\n/g, '\n').trim() + '\n',
  };
  l.hash = bodyHash(l.body);
  return writeLesson(dir, l);
}

// ── Upsert into a store ───────────────────────────────────────────────────────
// Match order: id (same lesson re-synced) → hash → same title within 7 days
// (recurrence). Tombstoned ids are refused. Returns { action, lesson }.
//
// Same-id semantics: by default the incoming copy's content is taken only when
// its `updated` is newer. With `authoritative: true` (project → global sync, where
// the project file is the author) any content difference is taken.

function daysBetween(a, b) {
  return Math.abs((Date.parse(a + 'T00:00:00Z') - Date.parse(b + 'T00:00:00Z')) / 86400000);
}

function sameContent(a, b) {
  return a.title === b.title && a.date === b.date && bodyHash(a.body) === bodyHash(b.body)
      && JSON.stringify([...(a.stack || [])].sort()) === JSON.stringify([...(b.stack || [])].sort());
}

function upsertLesson(dir, incoming, { now, authoritative = false } = {}) {
  if (readTombstones(dir).has(incoming.id)) return { action: 'tombstoned', lesson: null };
  const { lessons } = loadStore(dir);
  const ts = now || nowIso();
  const inHash = bodyHash(incoming.body);

  let existing = lessons.find(l => l.id === incoming.id);
  let action = 'updated';
  if (!existing) {
    existing = lessons.find(l => l.hash === inHash || bodyHash(l.body) === inHash)
            || lessons.find(l => l.title.trim().toLowerCase() === incoming.title.trim().toLowerCase()
                               && daysBetween(l.date, incoming.date) <= RECURRENCE_WINDOW_DAYS);
    action = existing ? 'recurrence' : 'created';
  }

  if (!existing) {
    // New to this store: carry the content's own timestamps, not the sync time.
    const l = { ...stripRuntime(incoming), schema: SCHEMA, hash: inHash, created: incoming.created || ts, updated: incoming.updated || ts };
    return { action, lesson: writeLesson(dir, l) };
  }

  const merged = stripRuntime(existing);
  merged.projects = [...new Set([...(existing.projects || []), ...(incoming.projects || [])])];
  merged.stack    = [...new Set([...(existing.stack || []), ...(incoming.stack || [])])];
  if (action === 'recurrence') {
    merged.seen = (existing.seen || 1) + 1;
    merged.updated = [existing.updated || '', incoming.updated || ''].sort().pop() || ts;
  } else {
    merged.seen = Math.max(existing.seen || 1, incoming.seen || 1);
    const take = authoritative ? !sameContent(existing, incoming) : (incoming.updated || '') > (existing.updated || '');
    if (take) {
      merged.title = incoming.title; merged.date = incoming.date;
      merged.stack = [...new Set([...(incoming.stack || []), ...merged.stack])];
      merged.body = incoming.body; merged.hash = inHash;
      merged.updated = authoritative ? [incoming.updated || '', ts].sort().pop() : incoming.updated;
      if (incoming.generated_by && !merged.generated_by) merged.generated_by = incoming.generated_by;
    }
  }
  if (JSON.stringify(merged) === JSON.stringify(stripRuntime(existing))) return { action: 'unchanged', lesson: existing }; // nothing written
  return { action, lesson: writeLesson(dir, merged) };
}
const upsertGlobal = upsertLesson; // historical name

// ── Delete (with tombstone) ───────────────────────────────────────────────────

function deleteLesson(dir, id) {
  const l = findById(dir, id);
  appendTombstone(dir, id); // tombstone even if the file is already gone
  if (!l) return false;
  fs.unlinkSync(path.join(lessonsDir(dir), l.file));
  return true;
}

// ── Rollups: schema-1 markdown (grep compatibility) + OKF index ───────────────

function rollupMarkdown(dir, lessons) {
  // e.g. ".claude/skill-trace" — relative to the project root (or home)
  const rel = path.relative(path.dirname(path.dirname(dir)), dir).replace(/\\/g, '/') || dir;
  const head = [
    `${GENERATED_MARK} from ${rel}/${LESSONS_DIR} — edit the lesson files, not this -->`,
    '<!-- skill-trace-schema: 1 -->',
    '', '',
  ];
  const blocks = lessons.map(l => {
    const prov = l.projects.length ? ` <!-- ${l.projects.join(', ')} -->` : '';
    const stack = l.stack.length ? `**Stack:** ${l.stack.join(', ')}\n\n` : '';
    return `## [${l.date}] — ${l.title}${prov}\n\n${stack}${l.body.trimEnd()}\n`;
  });
  return head.join('\n') + blocks.join('\n');
}

function indexMarkdown(lessons) {
  const byStack = new Map();
  for (const l of lessons) for (const t of (l.stack.length ? l.stack : ['(untagged)'])) {
    if (!byStack.has(t)) byStack.set(t, []);
    byStack.get(t).push(l);
  }
  const lines = ['---', 'okf_version: "0.1"', 'type: Index', '---', '', '# Lessons', '',
    `${lessons.length} lesson${lessons.length === 1 ? '' : 's'} · generated by skill-trace; edit files under \`${LESSONS_DIR}/\`.`, ''];
  for (const [t, ls] of [...byStack.entries()].sort((a, b) => b[1].length - a[1].length || a[0].localeCompare(b[0]))) {
    lines.push(`## ${t} (${ls.length})`, '');
    for (const l of ls) lines.push(`* [${l.title}](${LESSONS_DIR}/${l.file}) — ${l.date}${l.seen > 1 ? ` · seen ×${l.seen}` : ''}`);
    lines.push('');
  }
  return lines.join('\n');
}

// Regenerate `<dir>/index.md` and, when `target` is given, the schema-1 rollup
// file (e.g. docs/skills.md or ~/.claude/global-skills.md).
function regenRollup(dir, target) {
  const { lessons } = loadStore(dir);
  ensureStore(dir);
  fs.writeFileSync(path.join(dir, 'index.md'), indexMarkdown(lessons), 'utf8');
  if (target) {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, rollupMarkdown(dir, lessons), 'utf8');
  }
  return lessons.length;
}

function isGenerated(file) {
  try { return fs.readFileSync(file, 'utf8').replace(/^﻿/, '').startsWith(GENERATED_MARK); } catch { return false; }
}

// ── Legacy (schema 1) parsing, migration, absorption ──────────────────────────
// Deliberately self-contained (does not require server.js) so the server can
// depend on this module without a cycle.

const LEGACY_HEADER_RE = /^## \[?(\d{4}-\d{2}-\d{2})\]? — (.+?)(?:\s+<!--\s*(.+?)\s*-->)?\s*$/;

function parseLegacyMd(content) {
  content = String(content).replace(/^﻿/, '').replace(/\r\n/g, '\n');
  const blocks = content.split(/(?=^## (?:\[?\d{4}-\d{2}-\d{2}\]?))/m).filter(b => /^## \[?\d{4}-\d{2}-\d{2}\]?/.test(b.trim()));
  const entries = [];
  for (const block of blocks) {
    const [first, ...rest] = block.trim().split('\n');
    const m = first.match(LEGACY_HEADER_RE);
    if (!m) continue;
    const [, date, rawTitle, prov] = m;
    let body = rest.join('\n').trim();
    let stack = [];
    const sm = body.match(/^\*\*Stack:\*\*\s*(.+)$/m);
    if (sm) { stack = sm[1].split(',').map(s => s.trim().toLowerCase()).filter(Boolean); body = body.replace(sm[0], '').trim(); }
    const projects = (prov || '').split(',').map(p => p.trim()).filter(p => p && !/^v\d+\s*\|?$/.test(p));
    entries.push({ title: rawTitle.trim(), date, stack, projects, body: body + '\n' });
  }
  return entries;
}

function legacyToLesson(e, { generatedBy, projects, ts }) {
  return {
    id: ulid(), type: 'Lesson', schema: SCHEMA, title: e.title, date: e.date, stack: e.stack,
    projects: e.projects.length ? e.projects : (projects || []), seen: 1,
    ...(generatedBy ? { generated_by: generatedBy } : {}),
    created: `${e.date}T00:00:00Z`, updated: ts, body: e.body, hash: bodyHash(e.body),
  };
}

// Split a legacy single file into lesson files. Idempotent: a file that is
// already a generated rollup, or a missing file, is a no-op. The legacy file is
// RENAMED (never deleted) and a rollup regenerated in its place.
function migrateLegacy(mdPath, dir, { now, rename = true, generatedBy = 'migration', projects } = {}) {
  if (!fs.existsSync(mdPath)) return { migrated: 0, merged: 0, skipped: 'no legacy file' };
  if (isGenerated(mdPath)) return { migrated: 0, merged: 0, skipped: 'already a generated rollup' };
  const entries = parseLegacyMd(fs.readFileSync(mdPath, 'utf8'));
  ensureStore(dir);
  const ts = now || nowIso();
  let migrated = 0, merged = 0;
  for (const e of entries) {
    const r = upsertLesson(dir, legacyToLesson(e, { generatedBy, projects, ts }), { now: ts });
    if (r.action === 'created') migrated++; else if (r.action !== 'tombstoned') merged++;
  }
  let legacyRenamedTo = null;
  if (rename) {
    const stamp = ts.slice(0, 10).replace(/-/g, '');
    const base = mdPath.replace(/\.md$/i, '');
    legacyRenamedTo = `${base}.legacy-${stamp}.md`;
    for (let i = 2; fs.existsSync(legacyRenamedTo); i++) legacyRenamedTo = `${base}.legacy-${stamp}-${i}.md`;
    fs.renameSync(mdPath, legacyRenamedTo);
    regenRollup(dir, mdPath);
  }
  return { migrated, merged, total: entries.length, legacyRenamedTo };
}

// Bring a schema-1 markdown file into a store, whatever state it is in:
//   - missing                      → nothing
//   - hand-written, no store yet   → migrate (rename + regenerate rollup)
//   - otherwise (rollup, possibly with entries appended by hand or by an old
//     hook, or a hand-written file next to an existing store) → absorb every
//     entry whose body hash the store does not have, then regenerate the rollup.
// This is what keeps a hand-edited rollup safe: nothing typed into it is lost.
function absorbFile(mdPath, dir, { generatedBy = 'hook', projects, now } = {}) {
  if (!fs.existsSync(mdPath)) return { action: 'none' };
  const hasStore = fs.existsSync(lessonsDir(dir));
  if (!isGenerated(mdPath) && !hasStore) {
    return { action: 'migrated', ...migrateLegacy(mdPath, dir, { now, generatedBy: 'migration', projects }) };
  }
  const known = new Set(loadStore(dir).lessons.map(l => l.hash));
  const ts = now || nowIso();
  let added = 0;
  for (const e of parseLegacyMd(fs.readFileSync(mdPath, 'utf8'))) {
    if (known.has(bodyHash(e.body))) continue;
    const r = upsertLesson(dir, legacyToLesson(e, { generatedBy, projects, ts }), { now: ts });
    if (r.action !== 'tombstoned' && r.action !== 'unchanged') added++;
  }
  if (added || !isGenerated(mdPath)) regenRollup(dir, mdPath);
  return { action: 'absorbed', added };
}

// ── Project identity ──────────────────────────────────────────────────────────

// Which project does this file belong to, and is it a legacy/rollup markdown?
// Recognizes docs/skills.md, a lesson file inside .claude/skill-trace/lessons/,
// and any path matching SKILL_TRACE_SOURCE_PATTERN (a regex; opt-in).
function projectRoot(filePath) {
  const n = String(filePath).replace(/\\/g, '/');
  let m = n.match(/^(.*)\/docs\/skills\.md$/i);
  if (m) return { root: m[1], legacyMd: filePath };
  m = n.match(/^(.*)\/\.claude\/skill-trace\/lessons\/[^/]+\.md$/i);
  if (m) return { root: m[1] };
  const pat = process.env.SKILL_TRACE_SOURCE_PATTERN;
  if (pat) {
    let re; try { re = new RegExp(pat); } catch { re = null; }
    if (re && re.test(filePath)) {
      const dir = path.dirname(filePath);
      return { root: /[/\\]docs$/i.test(dir) ? path.dirname(dir) : dir, legacyMd: filePath };
    }
  }
  return null;
}

// Stable project slug: git remote name (survives folder renames), else folder name.
function projectSlug(root) {
  try {
    const url = execFileSync('git', ['-C', root, 'config', '--get', 'remote.origin.url'],
      { encoding: 'utf8', timeout: 2000, stdio: ['ignore', 'pipe', 'ignore'] }).trim();
    const slug = url.replace(/\.git$/, '').split('/').pop().split(':').pop();
    if (slug) return slug;
  } catch { /* not a git repo, or no remote */ }
  return path.basename(path.resolve(root)) || 'unknown-project';
}

// ── Project → global sync ─────────────────────────────────────────────────────
// The single write path the hooks and the log-lesson skill go through.
//   1. bring docs/skills.md (or the custom legacy file) into the project store
//   2. re-bless hand-edited project lessons (refresh hash + updated)
//   3. regenerate the project rollup (+ index)
//   4. record the source (trusted=no if new) and where it lives
//   5. if the source is trusted: mirror every project lesson into the global
//      store (project copy is authoritative) and regenerate the global rollup
// Runs under the sync-wide lock shared with the trust registry.

function syncProject(root, slug, { legacyMd, now } = {}) {
  const paths = storePaths({ projectDir: root });
  const pdir = paths.project;
  const md = legacyMd || paths.legacyProjectMd;
  slug = slug || projectSlug(root);
  return trust.withLock(() => {
    const absorbed = absorbFile(md, pdir, { generatedBy: 'hook', projects: [slug], now });
    const { lessons } = loadStore(pdir);
    const ts = now || nowIso();
    for (const l of lessons) {
      if (l.edited) { l.hash = bodyHash(l.body); l.updated = ts; writeLesson(pdir, stripRuntime(l)); }
    }
    if (lessons.length) regenRollup(pdir, md);
    trust.recordSource(slug, root, { locked: true });
    const trusted = trust.isTrusted(slug);
    let synced = 0;
    if (trusted && lessons.length) {
      absorbFile(paths.legacyGlobalMd, paths.global, { generatedBy: 'hook', now }); // never clobber a hand-written global file
      for (const l of lessons) {
        const inc = { ...stripRuntime(l), projects: [...new Set([slug, ...(l.projects || [])])] };
        const r = upsertLesson(paths.global, inc, { now: ts, authoritative: true });
        if (r.action !== 'unchanged' && r.action !== 'tombstoned') synced++;
      }
      regenRollup(paths.global, paths.legacyGlobalMd);
    }
    return { slug, root, trusted, projectLessons: lessons.length, absorbed, synced };
  }, { maxWaitMs: 10000 });
}

// ── CLI ───────────────────────────────────────────────────────────────────────

// Read all of stdin. Async on purpose: a synchronous readFileSync(0) on a Windows
// pipe is unreliable on older Node versions (returns empty / throws EOF), which
// made the hook silently do nothing on Node 20 runners.
function readStdin() {
  return new Promise(resolve => {
    let data = '';
    const stdin = process.stdin;
    stdin.setEncoding('utf8');
    stdin.on('data', c => { data += c; });
    // PowerShell 5.1 may prepend a UTF-8 BOM when piping into a native command.
    const done = () => resolve(data.replace(/^﻿/, ''));
    stdin.on('end', done);
    stdin.on('error', done);
    if (stdin.isTTY) resolve('');
  });
}

function debug(msg) { if (process.env.SKILL_TRACE_DEBUG) process.stderr.write(`skill-trace: ${msg}\n`); }

async function cli(argv) {
  const [cmd, ...rest] = argv;
  const flags = Object.fromEntries(rest.filter(a => a.startsWith('--')).map(a => { const [k, v] = a.slice(2).split('='); return [k, v ?? true]; }));
  const args = rest.filter(a => !a.startsWith('--'));
  const root = flags.project && flags.project !== true ? path.resolve(flags.project) : process.cwd();
  const paths = storePaths({ projectDir: root });
  const dir = flags.global ? paths.global : paths.project;
  const rollupTarget = flags.global ? paths.legacyGlobalMd : paths.legacyProjectMd;
  const out = o => process.stdout.write(JSON.stringify(o, null, 2) + '\n');

  switch (cmd) {
    case 'status': {
      const { lessons, warnings } = loadStore(dir);
      return out({ store: dir, lessons: lessons.length, edited: lessons.filter(l => l.edited).length, tombstones: readTombstones(dir).size, warnings });
    }
    case 'create': {
      // JSON on stdin: { title, date, stack[], body, generated_by? , project? }
      const input = JSON.parse(await readStdin());
      const slug = input.project || projectSlug(root);
      const l = createLesson(dir, { ...input, project: slug, generatedBy: input.generated_by || 'claude-code' });
      const r = flags.global ? (regenRollup(dir, rollupTarget), null) : syncProject(root, slug);
      return out({ created: l.id, file: l.file, store: dir, ...(r ? { trusted: r.trusted, syncedToGlobal: r.synced } : {}) });
    }
    case 'delete': {
      const ok = deleteLesson(dir, args[0]);
      regenRollup(dir, rollupTarget);
      return out({ deleted: ok, id: args[0] });
    }
    case 'regen':
      return out({ lessons: regenRollup(dir, rollupTarget), rollup: rollupTarget });
    case 'migrate':
      return out(migrateLegacy(rollupTarget, dir));
    case 'sync':
      return out(syncProject(root, flags.slug && flags.slug !== true ? flags.slug : undefined));
    case 'hook': {
      // Claude Code PostToolUse event on stdin. Never fails loudly: hooks must be silent.
      const raw = await readStdin();
      let event; try { event = JSON.parse(raw); } catch { debug(`hook: stdin is not JSON (${raw.length} bytes)`); return; }
      const file = event && event.tool_input && event.tool_input.file_path;
      if (!file) { debug('hook: event has no tool_input.file_path'); return; }
      const where = projectRoot(file);
      if (!where) { debug(`hook: not a lessons file, ignored: ${file}`); return; }
      try { return out(syncProject(where.root, undefined, { legacyMd: where.legacyMd })); }
      catch (err) { process.stderr.write(`skill-trace hook: ${err.message}\n`); return; }
    }
    default:
      process.stderr.write('usage: node store.js <status|create|delete <id>|regen|migrate|sync|hook> [--global] [--project=<dir>] [--slug=<slug>]\n');
      process.exit(2);
  }
}

if (require.main === module) {
  cli(process.argv.slice(2)).catch(err => { process.stderr.write(`store: ${err.message}\n`); process.exit(1); });
}

module.exports = {
  SCHEMA, DEFAULT_SOURCE_RE, storePaths, ulid, normalizeBody, bodyHash, parseLesson, serializeLesson, sections, extractSection,
  slugify, lessonFilename, loadStore, writeLesson, createLesson, upsertLesson, upsertGlobal, deleteLesson, readTombstones,
  regenRollup, rollupMarkdown, indexMarkdown, isGenerated, parseLegacyMd, migrateLegacy, absorbFile,
  projectRoot, projectSlug, syncProject,
};
