'use strict';

// forget() resolution rules, and the S7 correction: skill-trace never creates a
// docs/ folder in a project; a project that already had docs/skills.md keeps it
// regenerated. All paths redirected to temp dirs before the modules load.

const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const { join } = require('node:path');
const { tmpdir } = require('node:os');

const HOME = fs.mkdtempSync(join(tmpdir(), 'st-del-home-'));
process.env.SKILL_TRACE_TRUST_PATH   = join(HOME, '.claude', 'skill-trace-trust.txt');
process.env.SKILL_TRACE_SOURCES_PATH = join(HOME, '.claude', 'skill-trace-sources.txt');
process.env.SKILL_TRACE_GLOBAL_STORE = join(HOME, '.claude', 'skill-trace');
process.env.GLOBAL_SKILLS_MD_PATH    = join(HOME, '.claude', 'global-skills.md');
delete process.env.SKILL_TRACE_SOURCE_PATTERN;

const S = require('../store.js');

const files = dir => fs.existsSync(join(dir, 'lessons')) ? fs.readdirSync(join(dir, 'lessons')).filter(f => f.endsWith('.md')) : [];
const BODY = '**Problem:** p\n\n**Takeaway:** t\n';

test('forget: by id, by unique title fragment; ambiguous and unknown are refused; tombstone recorded', () => {
  const dir = fs.mkdtempSync(join(tmpdir(), 'st-del-'));
  const a = S.createLesson(dir, { title: 'Lock the file every writer touches', date: '2026-06-10', body: BODY, project: 'p' });
  const b = S.createLesson(dir, { title: 'Lock the registry too', date: '2026-06-11', body: BODY + 'b\n', project: 'p' });
  S.createLesson(dir, { title: 'Strip the BOM', date: '2026-06-12', body: BODY + 'c\n', project: 'p' });

  let r = S.forget(dir, 'lock');
  assert.equal(r.deleted, false);
  assert.equal(r.reason, 'ambiguous');
  assert.deepEqual(r.matches.map(m => m.title).sort(), ['Lock the file every writer touches', 'Lock the registry too']);
  assert.equal(files(dir).length, 3, 'nothing deleted on ambiguity');

  r = S.forget(dir, 'nothing like this');
  assert.deepEqual(r, { deleted: false, reason: 'no match', query: 'nothing like this' });
  assert.deepEqual(S.forget(dir, '   '), { deleted: false, reason: 'empty query' });

  r = S.forget(dir, 'REGISTRY');
  assert.equal(r.deleted, true);
  assert.equal(r.id, b.id, 'case-insensitive unique fragment');
  assert.equal(files(dir).length, 2);

  r = S.forget(dir, a.id);
  assert.equal(r.deleted, true);
  assert.equal(r.title, 'Lock the file every writer touches');
  assert.equal(files(dir).length, 1);
  assert.deepEqual([...S.readTombstones(dir)].sort(), [a.id, b.id].sort());
  assert.equal(S.upsertLesson(dir, { ...a, file: undefined }).action, 'tombstoned', 'cannot come back');
});

test('S7: a project without docs/skills.md never gets a docs/ folder; index.md is still written', () => {
  const root = join(fs.mkdtempSync(join(tmpdir(), 'st-del-proj-')), 'fresh');
  fs.mkdirSync(root, { recursive: true });
  const pdir = join(root, '.claude', 'skill-trace');
  S.createLesson(pdir, { title: 'Fresh project lesson', date: '2026-06-10', body: BODY, project: 'fresh' });
  const r = S.syncProject(root, 'fresh');
  assert.equal(r.projectLessons, 1);
  assert.ok(!fs.existsSync(join(root, 'docs')), 'no docs/ folder created');
  assert.ok(fs.existsSync(join(pdir, 'index.md')), 'store index generated');
  assert.match(fs.readFileSync(join(pdir, 'index.md'), 'utf8'), /Fresh project lesson/);
});

test('S7: a project that already had docs/skills.md keeps it regenerated after every sync', () => {
  const root = join(fs.mkdtempSync(join(tmpdir(), 'st-del-proj-')), 'legacy');
  fs.mkdirSync(join(root, 'docs'), { recursive: true });
  fs.writeFileSync(join(root, 'docs', 'skills.md'), '## [2026-06-10] — Legacy lesson <!-- legacy -->\n\n**Problem:** p\n', 'utf8');
  S.syncProject(root, 'legacy');
  const pdir = join(root, '.claude', 'skill-trace');
  assert.equal(files(pdir).length, 1);
  S.createLesson(pdir, { title: 'Second lesson', date: '2026-06-11', body: BODY, project: 'legacy' });
  S.syncProject(root, 'legacy');
  const rollup = fs.readFileSync(join(root, 'docs', 'skills.md'), 'utf8');
  assert.ok(rollup.startsWith('<!-- generated by skill-trace'));
  assert.equal((rollup.match(/^## \[/gm) || []).length, 2, 'rollup carries both lessons');
  // forget via CLI path semantics: regen only touches the rollup because it exists
  const r = S.forget(pdir, 'Second');
  assert.equal(r.deleted, true);
  S.regenRollup(pdir, fs.existsSync(join(root, 'docs', 'skills.md')) ? join(root, 'docs', 'skills.md') : undefined);
  assert.equal((fs.readFileSync(join(root, 'docs', 'skills.md'), 'utf8').match(/^## \[/gm) || []).length, 1);
});
