'use strict';

// End-to-end server tests: boot the real server.js on a free port with every
// path pointed at a temp directory, then exercise migration, the store-backed
// API shape, and the legacy-append compatibility path.

const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const { join } = require('node:path');
const { tmpdir } = require('node:os');
const { spawn } = require('node:child_process');
const net = require('node:net');

const SERVER = join(__dirname, '..', 'server.js');
const sleep = ms => new Promise(r => setTimeout(r, ms));

function freePort() {
  return new Promise(res => { const s = net.createServer(); s.listen(0, '127.0.0.1', () => { const p = s.address().port; s.close(() => res(p)); }); });
}

async function boot(home) {
  const port = await freePort();
  const child = spawn(process.execPath, [SERVER], {
    env: { ...process.env, GLOBAL_SKILLS_MD_PATH: join(home, 'global-skills.md'), SKILL_TRACE_GLOBAL_STORE: join(home, 'skill-trace'), GLOBAL_SKILLS_PORT: String(port) },
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  let log = '';
  child.stdout.on('data', d => { log += d; });
  child.stderr.on('data', d => { log += d; });
  for (let i = 0; i < 60; i++) {
    try { await fetch(`http://127.0.0.1:${port}/api/skills`); break; } catch { await sleep(100); }
  }
  const api = async (path, init) => (await fetch(`http://127.0.0.1:${port}${path}`, init)).json();
  return { child, port, api, log: () => log, stop: () => child.kill() };
}

const LEGACY = `# Global Skills Log
<!-- skill-trace-schema: 1 -->

## [2026-06-10] — HTMX partial detection <!-- app-a -->

**Stack:** HTMX, Express

**Problem:** Routes serve both full pages and partials.

**Solution:** Check the hx-request header.

**Takeaway:** Always check req.headers['hx-request'].

## [2026-06-12] — Second lesson <!-- app-b -->

**Problem:** p2

**Takeaway:** t2
`;

test('startup migrates a legacy global-skills.md into the store and serves it', async () => {
  const home = fs.mkdtempSync(join(tmpdir(), 'st-srv-'));
  fs.writeFileSync(join(home, 'global-skills.md'), LEGACY, 'utf8');
  const srv = await boot(home);
  try {
    const rows = await srv.api('/api/skills');
    assert.equal(rows.length, 2);
    assert.equal(rows[0].title, 'Second lesson', 'newest first');
    assert.match(rows[0].id, /^[0-9A-HJKMNP-TV-Z]{26}$/, 'ULID ids, not array indexes');
    assert.equal(rows[0].seen, 1);
    assert.equal(rows[0].edited, false);
    assert.match(rows[0].meta, /^id: [0-9A-Z]{26}\ntype: Lesson\nschema: 2\ntitle: Second lesson\n/, 'meta is the frontmatter text');
    assert.deepEqual(rows[1].stack, ['htmx', 'express']);
    assert.equal(rows[1].takeaway, "Always check req.headers['hx-request'].");

    const lessons = fs.readdirSync(join(home, 'skill-trace', 'lessons'));
    assert.equal(lessons.length, 2);
    assert.ok(fs.existsSync(join(home, 'skill-trace', 'index.md')));
    assert.ok(fs.readdirSync(home).some(f => /^global-skills\.legacy-\d{8}\.md$/.test(f)), 'legacy renamed, not deleted');
    assert.ok(fs.readFileSync(join(home, 'global-skills.md'), 'utf8').startsWith('<!-- generated by skill-trace'), 'rollup regenerated in place');
    assert.match(srv.log(), /migrated legacy log — 2 lessons/);
  } finally { srv.stop(); }
});

test('compat: an entry appended to the rollup by the old hook is absorbed into the store', async () => {
  const home = fs.mkdtempSync(join(tmpdir(), 'st-srv-'));
  fs.writeFileSync(join(home, 'global-skills.md'), LEGACY, 'utf8');
  const srv = await boot(home);
  try {
    assert.equal((await srv.api('/api/skills')).length, 2);
    // simulate the current PostToolUse hook: append a schema-1 block to the rollup
    fs.appendFileSync(join(home, 'global-skills.md'), `\n## [2026-06-20] — Appended by hook <!-- app-c -->\n\n**Stack:** node\n\n**Problem:** p3\n\n**Takeaway:** t3\n`, 'utf8');
    let rows;
    for (let i = 0; i < 40; i++) { rows = await srv.api('/api/skills'); if (rows.length === 3) break; await sleep(150); }
    if (rows.length !== 3) { await srv.api('/api/sync', { method: 'POST' }); rows = await srv.api('/api/skills'); } // fs.watch is best-effort on some CI runners
    assert.equal(rows.length, 3);
    assert.equal(rows[0].title, 'Appended by hook');
    assert.deepEqual(rows[0].stack, ['node']);
    assert.equal(fs.readdirSync(join(home, 'skill-trace', 'lessons')).length, 3, 'now a lesson file');
    const rollup = fs.readFileSync(join(home, 'global-skills.md'), 'utf8');
    assert.ok(rollup.startsWith('<!-- generated by skill-trace'), 'rollup regenerated');
    assert.equal((rollup.match(/^## \[/gm) || []).length, 3);
    // a second sync must not duplicate it
    await srv.api('/api/sync', { method: 'POST' });
    assert.equal((await srv.api('/api/skills')).length, 3);
  } finally { srv.stop(); }
});

test('GET /api/lessons/:id returns one; DELETE removes it, tombstones it, regenerates the rollup, 404s afterwards', async () => {
  const home = fs.mkdtempSync(join(tmpdir(), 'st-srv-'));
  fs.writeFileSync(join(home, 'global-skills.md'), LEGACY, 'utf8');
  const srv = await boot(home);
  try {
    const rows = await srv.api('/api/skills');
    const victim = rows.find(r => r.title === 'Second lesson');
    const one = await srv.api(`/api/lessons/${victim.id}`);
    assert.equal(one.title, 'Second lesson');
    assert.ok(one.meta.includes(`id: ${victim.id}`));

    const del = await srv.api(`/api/lessons/${victim.id}`, { method: 'DELETE' });
    assert.deepEqual(del, { ok: true, id: victim.id, count: 1 });
    assert.deepEqual((await srv.api('/api/skills')).map(r => r.title), ['HTMX partial detection']);
    assert.equal(fs.readdirSync(join(home, 'skill-trace', 'lessons')).length, 1, 'file removed');
    assert.equal(fs.readFileSync(join(home, 'skill-trace', 'tombstones.txt'), 'utf8').trim(), victim.id);
    assert.ok(!fs.readFileSync(join(home, 'global-skills.md'), 'utf8').includes('Second lesson'), 'rollup regenerated without it');

    const miss = await fetch(`http://127.0.0.1:${srv.port}/api/lessons/${victim.id}`);
    assert.equal(miss.status, 404);
    const again = await fetch(`http://127.0.0.1:${srv.port}/api/lessons/${victim.id}`, { method: 'DELETE' });
    assert.equal(again.status, 404, 'deleting twice is a 404, not a crash');
    const bad = await fetch(`http://127.0.0.1:${srv.port}/api/lessons/${victim.id}`, { method: 'POST' });
    assert.equal(bad.status, 405);
  } finally { srv.stop(); }
});

test('no legacy file and no store → empty, no crash; a legacy file appearing later is migrated on sync; dedupe route is gone', async () => {
  const home = fs.mkdtempSync(join(tmpdir(), 'st-srv-'));
  const srv = await boot(home);
  try {
    assert.deepEqual(await srv.api('/api/skills'), []);
    assert.ok(!fs.existsSync(join(home, 'skill-trace', 'lessons')), 'nothing created for an empty install');
    fs.writeFileSync(join(home, 'global-skills.md'), LEGACY, 'utf8');
    await srv.api('/api/sync', { method: 'POST' });
    assert.equal((await srv.api('/api/skills')).length, 2);
    const gone = await fetch(`http://127.0.0.1:${srv.port}/api/dedupe`, { method: 'POST' });
    assert.equal(gone.status, 404, 'legacy dedupe route removed; the store dedups on write');
  } finally { srv.stop(); }
});
